/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 colour system (retained — used by existing JSX)
        "inverse-primary": "#a83900",
        "outline": "#a98a7f",
        "surface-bright": "#463630",
        "tertiary-fixed-dim": "#6cd2ff",
        "surface-dim": "#1d100c",
        "on-surface": "#f7ddd5",
        "primary-fixed": "#ffdbcf",
        "tertiary-container": "#00a6d6",
        "surface-container": "#2a1c17",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-container": "#5c1c00",
        "on-tertiary-fixed": "#001f2a",
        "secondary-container": "#474746",
        "on-secondary": "#303030",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#802900",
        "secondary": "#c8c6c5",
        "surface-container-high": "#352721",
        "on-tertiary": "#003547",
        "outline-variant": "#594139",
        "surface": "#1d100c",
        "surface-tint": "#ffb59a",
        "on-tertiary-fixed-variant": "#004d65",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-variant": "#41312c",
        "primary": "#ffb59a",
        "inverse-surface": "#f7ddd5",
        "on-error": "#690005",
        "on-secondary-container": "#b7b5b4",
        "background": "#1d100c",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#1b1b1c",
        "surface-container-lowest": "#170b07",
        "surface-container-highest": "#41312c",
        "surface-container-low": "#261813",
        "primary-container": "#ff6b2c",
        "error-container": "#93000a",
        "on-background": "#f7ddd5",
        "on-tertiary-container": "#003648",
        "on-surface-variant": "#e2bfb3",
        "on-primary": "#5b1b00",
        "on-primary-fixed": "#380d00",
        "inverse-on-surface": "#3c2d27",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#bfe9ff",
        "primary-fixed-dim": "#ffb59a",
        "tertiary": "#6cd2ff",
        
        // Semantic design tokens — Hallmark Grid Theme
        "paper":            "var(--color-paper)",
        "paper-2":          "var(--color-paper-2)",
        "paper-3":          "var(--color-paper-3)",
        "ink":              "var(--color-ink)",
        "muted":            "var(--color-muted)",
        "dim":              "var(--color-dim)",
        "rule":             "var(--color-rule)",
        "accent":           "var(--color-accent)",
        "accent-dim":       "var(--color-accent-dim)",
        
        // Semantic aliases
        "bg-base":          "var(--color-paper)",
        "surface-level-1":  "var(--color-paper)",
        "surface-level-2":  "var(--color-paper-2)",
        "border-subtle":    "var(--color-rule)",
        "border-hover":     "var(--color-ink)",
        "accent-primary":   "var(--color-accent)",
        "accent-hover":     "var(--color-accent-hover)",
      },
      borderRadius: {
        "DEFAULT": "0px",
        "none": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      spacing: {
        "unit": "4px",
        "lg": "24px",
        "md": "16px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "sm": "8px",
        "xl": "40px",
        "xs": "4px",
        "2xl": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        "sans": ["Archivo", "sans-serif"],
        "display": ["Archivo", "sans-serif"],
        "body": ["Archivo", "sans-serif"],
        "label-caps": ["Archivo", "sans-serif"],
        "headline-md": ["Archivo", "sans-serif"],
        "code-sm": ["Archivo", "monospace"],
        "headline-sm": ["Archivo", "sans-serif"],
        "display-lg-mobile": ["Archivo", "sans-serif"],
        "body-sm": ["Archivo", "sans-serif"],
        "body-lg": ["Archivo", "sans-serif"],
        "body-md": ["Archivo", "sans-serif"],
        "display-lg": ["Archivo", "sans-serif"],
        "code-md": ["Archivo", "monospace"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.09em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["56px", { lineHeight: "56px", letterSpacing: "-0.045em", fontWeight: "800" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "500" }]
      },
      backgroundImage: {
        'grid-pattern': "repeating-linear-gradient(to right, var(--color-rule) 0, var(--color-rule) 1px, transparent 1px, transparent calc(100% / 12))",
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
