spring.application.name=url-shortener-sb



spring.datasource.url=jdbc:mysql://localhost:3306/linkengine
spring.datasource.username=root
spring.datasource.password=arbiclad
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
jwt.secret=XUkf1Qq7UVPqBfpWkI9c59Ufdg44V1MmyfXR4njdE6m
jwt.expiration=172800000